# Generated by Django 6.0 on 2025-12-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authorName', models.FloatField()),
                ('short_description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(upload_to='product-images/')),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('politics', 'Politics'), ('health', 'Health'), ('business', 'Business'), ('education', 'Education'), ('food', 'Food'), ('travel', 'Travel'), ('art', 'Art'), ('music', 'Music'), ('science', 'Science'), ('others', 'Others')], max_length=20)),
            ],
        ),
    ]
