# Generated by Django 6.0 on 2025-12-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='articleParagrah',
            field=models.TextField(default='No content available'),
        ),
    ]
