# Generated by Django 6.0 on 2025-12-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_articles_articleparagrah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='authorName',
            field=models.CharField(max_length=50),
        ),
    ]
