# Generated by Django 6.0 on 2025-12-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_alter_articles_authorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='readtime',
            field=models.IntegerField(default=4),
        ),
    ]
